english: VictorGonzalez.en.tex
	lualatex VictorGonzalez.en.tex

spanish: VictorGonzalez.es.tex
	lualatex VictorGonzalez.es.tex
	
clean:
	rm *.aux *.bcf *.log *.out *.xml

all: english clean spanish clean