english: VictorGonzalez.en.tex
	xelatex VictorGonzalez.en.tex

spanish: VictorGonzalez.es.tex
	xelatex VictorGonzalez.es.tex
	
clean:
	rm *.aux *.bcf *.log *.out *.xml

all: english clean spanish clean